---
- hosts:
    - vehicles
    - ndm
  gather_facts: false

  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Install Docker
      block:
        - name: Update apt cache
          apt: update_cache=yes cache_valid_time=3600
        - name: Upgrade all apt packages
          apt: upgrade=dist
        - name: Install dependencies
          apt:
            name: "{{ packages }}"
            state: present
            update_cache: yes
          vars:
            packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - gnupg-agent
            - python3-pip
        - name: Add an apt signing key for Docker
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Add apt repository for stable version
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
            state: present
        - name: Install Docker
          apt:
            name: "{{ packages }}"
            state: present
            update_cache: yes
          vars:
            packages:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - python3-docker
        - name: Ensure docker deamon is running
          service:
            name: docker
            state: started
            enabled: yes

        - name: Install nvidia-docker2
          shell: |
            # TODO need to figure out how to get this command to prompt with "-y" because vm is getting stuck
            # distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
            # && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
            # && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
            # sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            # sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      
            sudo apt-get update
            sudo apt-get install -y nvidia-docker2

        - name: Restart Docker
          service:
            name: docker
            state: restarted
          tags: nvidia-docker

        - name: Ensure group "docker" exists
          ansible.builtin.group:
            name: docker
            state: present
        - name: Add user to docker group
          user:
            name: "{{ansible_user}}"
            group: docker
      become: True

    - name: Clone OpenCDA repo
      ansible.builtin.git:
        repo: https://github.com/tlandle/OpenCDA.git
        dest: /home/azureuser/OpenCDA
        version: ecloud
        force: True
      become: True

    - name: Build docker image using DockerFile
      docker_image:
        name: vehicle-sim
        build:
          path: /home/azureuser/OpenCDA
        source: build
      become: True

    # sudo nvidia-persistenced --user azureuser
    # nvidia-smi
    # apt search nvidia-driver
    # export CUDA_VISIBLE_DEVICES=0,1

    - name: Nvidia Driver Setup
      block:
        - name: Install Nvidia Driver
          apt:
            name:
              - nvidia-cuda-toolkit
              # - nvidia-driver-515
              # - nvidia-dkms-515
              - nvidia-driver-460
              - nvidia-dkms-460
            state: present

        - name: Reboot the VM
          reboot:
      become: True






