---
- hosts: vehicles
  gather_facts: false

  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Get details of all images
      docker_host_info:
        images: yes
        verbose_output: yes
      register: image_info
    - name: Remove all images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ image_info.images | map(attribute='Id') | list }}"
