---
- hosts: vehicles
  gather_facts: false

  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Create nvidia-docker Container
      block:
      - name: Create Container with Perception
        shell: | 
          nvidia-docker run --gpus all -d --network=host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY vehicle-sim --apply_ml
        with_sequence: count={{ containers_per_vm }}
        when: perception_active
      - name: Create Container without Perception
        shell: | 
          nvidia-docker run --gpus all -d --network=host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY vehicle-sim
        with_sequence: count={{ containers_per_vm }}
        when: not perception_active
      become: True

- hosts: ndm
  gather_facts: false

  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Create nvidia-docker Container
      block:
      - name: Create Container with Perception
        shell: | 
          nvidia-docker run --gpus all -d --network=host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY vehicle-sim --apply_ml
        with_sequence: count={{ containers_per_ndm_vm }}
        when: perception_active
      - name: Create Container without Perception
        shell: | 
          nvidia-docker run --gpus all -d --network=host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY vehicle-sim
        with_sequence: count={{ containers_per_ndm_vm }}
        when: not perception_active
      become: True
