local:
  carla_server_public_ip: localhost
  vehicle_client_public_ip: localhost
  clients:
    client_machine:
      machine_name: localhost
      vehicle_client_public_ip: localhost
      vehicle_client_dns: localhost

azure:
  carla_server_public_ip: '20.122.64.203' # server
  ecloud_server_public_ip: '20.122.64.203' # server
  # *must* be set to public IP *on* client machine(s) so they can send to ecloud server 
  clients:
    client_machine:
      machine_name: ndm
      vehicle_client_public_ip: '20.172.248.156'
      vehicle_client_dns: ''

multinode:
  carla_server_public_ip: '20.122.64.203' # server
  ecloud_server_public_ip: '20.122.64.203' # server
  # *must* be set to public IP *on* client machine(s) so they can send to ecloud server 
  clients:
    client_machine:
      machine_name: ndm
      vehicle_client_public_ip: '20.172.248.156'
      vehicle_client_dns: ''
    client_machine:
      machine_name: client4
      vehicle_client_public_ip: '20.242.82.41'
      vehicle_client_dns: ''
    client_machine:
      machine_name: client3
      vehicle_client_public_ip: '172.200.91.133'
      vehicle_client_dns: ''
    client_machine:
      machine_name: client2
      vehicle_client_public_ip: '172.171.196.63'
      vehicle_client_dns: ''
    client_machine:
      machine_name: client1
      vehicle_client_public_ip: '172.190.137.118'
      vehicle_client_dns: '' 

log_level: 'INFO' # deprecated
