---
# use this command to execute this file
# ansible-playbook azure-vm-create.yml --extra-vars "name=<virtualmachine_name>"

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - ../vars/vars.yml
  tasks:
    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: car-client-vm-1
        vm_size: Standard_D8s_v3
        ssh_password_enabled: true
        admin_username: "{{ username }}"
        admin_password: "{{ password }}"
        image:
          offer: 0001-com-ubuntu-server-focal
          publisher: canonical
          sku: 20_04-lts-gen2
          version: latest
