---
- name: Stop Azure VM
  hosts: localhost
  connection: local
  vars_files:
    - ./vars/vars.yml
  tasks:
    - name: Start virtual machines
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ item }}"
      loop: "{{ vehicle_vms }}"

