---
- hosts: vehicles
  gather_facts: false

  vars_prompt:
    - name: password
      prompt: "Enter password for ssh user"

  vars:
    ansible_user: azureuser
    ansible_password: "{{ password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    default_container_image: vehicle-sim
    default_container_name: vehicle-container
    create_containers: 4

  tasks:
    - name: Create container
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        state: started
        network_mode: host
        detach: True
      with_sequence: count={{ create_containers }}
      become: True


